import React, { useEffect, useState } from 'react';
import { BarChart3, Users, Leaf, Calendar, TrendingUp, Download, FileText } from 'lucide-react';
import { api } from '../../services/api';
import { PageHeader, StatCard, Btn, Spinner, Select, FormField } from '../../components/ui';
import { jsPDF } from 'jspdf';

export default function ReportsPage() {
  const [notification, setNotification] = useState(null);
  const [generating, setGenerating] = useState(false);
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [reportType, setReportType] = useState('total');
  const [selectedMonth, setSelectedMonth] = useState(new Date().getMonth() + 1);
  const [selectedYear, setSelectedYear] = useState(new Date().getFullYear());

  const months = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
  ];
  const years = Array.from({ length: 5 }, (_, i) => new Date().getFullYear() - i);

  useEffect(() => {
    api.getReport().then(d => { setReport(d); setLoading(false); });
  }, []);

  const handleGenerate = async () => {
    try {
      setGenerating(true);
      const periodLabel = reportType === 'monthly' ? `${months[selectedMonth - 1]} ${selectedYear}` : 
                        reportType === 'yearly' ? `${selectedYear}` : 'All Time';
      
      await api.generateReport({ type: reportType, month: selectedMonth, year: selectedYear });
      
      const doc = new jsPDF();
      doc.setFont("helvetica", "bold");
      doc.setFontSize(24);
      doc.setTextColor(16, 185, 129); // emerald-500
      doc.text("EcoGest", 105, 30, { align: "center" });
      
      doc.setFontSize(18);
      doc.setTextColor(30, 41, 59); // slate-800
      doc.text(`${reportType.toUpperCase()} Environmental Report`, 105, 45, { align: "center" });
      
      doc.setFontSize(14);
      doc.setTextColor(100, 116, 139); // slate-400
      doc.text(`Period: ${periodLabel}`, 105, 55, { align: "center" });
      
      doc.setDrawColor(226, 232, 240); // slate-200
      doc.line(20, 65, 190, 65);
      
      doc.setFontSize(12);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(30, 41, 59);
      doc.text(`Generated at: ${new Date().toLocaleString()}`, 20, 75);
      doc.text(`Responsible: ${api.currentUser?.name || 'N/A'}`, 20, 82);

      doc.setFont("helvetica", "bold");
      doc.text("Core Metrics:", 20, 95);
      doc.setFont("helvetica", "normal");
      doc.text(`• Total Activities: ${report.total_activities}`, 30, 105);
      doc.text(`• Completed Activities: ${report.completed_activities}`, 30, 112);
      doc.text(`• Total Participants involved: ${report.participants}`, 30, 119);
      doc.text(`• Planning Meetings held: ${report.meetings}`, 30, 126);
      doc.text(`• Global Engagement Rate: ${report.engagement_rate}`, 30, 133);
      doc.text(`• Active Projects monitored: ${report.projects}`, 30, 140);

      doc.setFont("helvetica", "bold");
      doc.text("Executive Summary:", 20, 155);
      doc.setFont("helvetica", "normal");
      const summary = `The project during ${periodLabel} has achieved a ${Math.round((report.completed_activities / report.total_activities) * 100)}% completion rate. We have successfully engaged ${report.participants} unique participants across ${report.projects} distinct projects. This ${reportType} report for ${periodLabel} highlights our commitment to sustainability and community involvement.`;
      const splitSummary = doc.splitTextToSize(summary, 170);
      doc.text(splitSummary, 20, 165);

      doc.setFontSize(10);
      doc.setTextColor(150);
      doc.text("This report was automatically generated by the EcoGest Platform.", 105, 280, { align: "center" });
      
      doc.save(`EcoGest_Report_${reportType}_${periodLabel.replace(' ', '_')}.pdf`);
      
      setGenerating(false);
      setNotification({ msg: `PDF ${reportType} report (${periodLabel}) downloaded!`, type: 'success' });
      setTimeout(() => setNotification(null), 3000);
    } catch (e) {
      setGenerating(false);
      setNotification({ msg: e.message, type: 'error' });
    }
  };

  if (loading) return <Spinner />;

  const completion = Math.round((report.completed_activities / report.total_activities) * 100);

  return (
    <div className="max-w-5xl space-y-8">
      <PageHeader
        title="Reports"
        subtitle="Project performance and engagement metrics"
        action={
          <div className="flex flex-wrap items-center gap-3 bg-white p-2 rounded-2xl border border-slate-200 shadow-sm animate-fade-left">
            <div className="flex items-center gap-2">
              <span className="text-xs font-bold text-slate-400 uppercase pl-2">Report:</span>
              <div className="w-36">
                <Select value={reportType} onChange={e => setReportType(e.target.value)} className="!py-1.5 !text-xs">
                  <option value="monthly">Monthly Report</option>
                  <option value="yearly">Yearly Report</option>
                  <option value="total">Total Report</option>
                </Select>
              </div>
            </div>

            {reportType === 'monthly' && (
              <div className="flex items-center gap-2 animate-fade-in">
                <div className="w-32">
                  <Select value={selectedMonth} onChange={e => setSelectedMonth(parseInt(e.target.value))} className="!py-1.5 !text-xs">
                    {months.map((m, i) => (
                      <option key={m} value={i + 1}>{m}</option>
                    ))}
                  </Select>
                </div>
              </div>
            )}

            {(reportType === 'monthly' || reportType === 'yearly') && (
              <div className="flex items-center gap-2 animate-fade-in">
                <div className="w-24">
                  <Select value={selectedYear} onChange={e => setSelectedYear(parseInt(e.target.value))} className="!py-1.5 !text-xs">
                    {years.map(y => (
                      <option key={y} value={y}>{y}</option>
                    ))}
                  </Select>
                </div>
              </div>
            )}

            <div className="h-6 w-px bg-slate-200 mx-1" />

            <Btn onClick={handleGenerate} disabled={generating} size="sm">
              <Download size={14} /> {generating ? 'Generating…' : 'Download PDF'}
            </Btn>
          </div>
        }
      />

      {/* KPI Cards */}
      <div className="grid grid-cols-2 lg:grid-cols-3 gap-4">
        <StatCard icon={Leaf}       label="Total Activities"     value={report.total_activities}     color="emerald" />
        <StatCard icon={TrendingUp} label="Completed Activities"  value={report.completed_activities} color="teal"    sub={`${completion}% completion rate`} />
        <StatCard icon={Users}      label="Total Participants"    value={report.participants}          color="blue"   />
        <StatCard icon={Calendar}   label="Meetings Held"         value={report.meetings}             color="purple" />
        <StatCard icon={BarChart3}  label="Engagement Rate"       value={report.engagement_rate}      color="amber"  />
        <StatCard icon={Leaf}       label="Active Projects"       value={report.projects}             color="emerald" />
      </div>

      {/* Completion Progress */}
      <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6">
        <h2 className="font-bold text-slate-800 mb-6">Activity Completion Progress</h2>
        <div className="space-y-5">
          {[
            { label: 'Activities Completed', value: report.completed_activities, max: report.total_activities, color: 'bg-emerald-500' },
            { label: 'Participant Engagement', value: report.participants, max: 200, color: 'bg-blue-500' },
            { label: 'Meetings Conducted', value: report.meetings, max: 10, color: 'bg-purple-500' },
          ].map(({ label, value, max, color }) => {
            const pct = Math.min(100, Math.round((value / max) * 100));
            return (
              <div key={label}>
                <div className="flex justify-between text-sm mb-2">
                  <span className="font-medium text-slate-700">{label}</span>
                  <span className="text-slate-500">{value} / {max}</span>
                </div>
                <div className="h-2.5 bg-slate-100 rounded-full overflow-hidden">
                  <div className={`h-full ${color} rounded-full transition-all duration-700`} style={{ width: `${pct}%` }} />
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Summary Text */}
      <div className="bg-gradient-to-br from-emerald-50 to-teal-50 border border-emerald-200 rounded-2xl p-6">
        <h2 className="font-bold text-emerald-800 mb-3 flex items-center gap-2"><BarChart3 size={20}/> Executive Summary</h2>
        <p className="text-slate-600 text-sm leading-relaxed">
          The EcoGest project has successfully executed <strong>{report.completed_activities}</strong> activities out of a planned <strong>{report.total_activities}</strong>, 
          achieving a completion rate of <strong>{completion}%</strong>. A total of <strong>{report.participants}</strong> participants 
          have been engaged across all environmental initiatives, with an overall engagement rate of <strong>{report.engagement_rate}</strong>. 
          The program is currently running across <strong>{report.projects}</strong> active project(s), 
          supported by <strong>{report.meetings}</strong> coordination meetings.
        </p>
      </div>

      {/* Toast Notification */}
      {notification && (
        <div className={`fixed bottom-4 right-4 px-6 py-4 rounded-xl shadow-xl border animate-fade-up z-50 flex items-center gap-3
          ${notification.type === 'success' ? 'bg-emerald-50 border-emerald-200 text-emerald-800' : 'bg-red-50 border-red-200 text-red-800'}`}
        >
          <span className="text-xl leading-none">{notification.type === 'success' ? '✅' : '⚠️'}</span>
          <p className="font-semibold text-sm">{notification.msg}</p>
          <button onClick={() => setNotification(null)} className="ml-2 text-current opacity-60 hover:opacity-100 font-bold">&times;</button>
        </div>
      )}
    </div>
  );
}
